spring:
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
    open-in-view: false
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect
        format_sql: true
  sql:
    init:
      schema-locations: classpath:schema.sql
      mode: always
  datasource:
    url: jdbc:mysql://localhost/${LOCAL_DB_NAME}
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: ${LOCAL_DB_USER}
    password: ${LOCAL_DB_PASSWORD}
  h2:
    console:
      enabled: true

security:
  jwt:
    token:
      secret-key: fjhbewhjbrfkelwdvhkewjkbwd
      expire-length: 3600000

cors:
  allowed-origin: http://localhost:3000

payment:
  toss:
    secret-key: localocal

management:
  server:
    port: 8080
  endpoints:
    web:
      base-path: /actuator
